// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/celestialtree.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Parents       []uint64               `protobuf:"varint,4,rep,packed,name=parents,proto3" json:"parents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitRequest) Reset() {
	*x = EmitRequest{}
	mi := &file_proto_celestialtree_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitRequest) ProtoMessage() {}

func (x *EmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_celestialtree_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitRequest.ProtoReflect.Descriptor instead.
func (*EmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_celestialtree_proto_rawDescGZIP(), []int{0}
}

func (x *EmitRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EmitRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmitRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EmitRequest) GetParents() []uint64 {
	if x != nil {
		return x.Parents
	}
	return nil
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_proto_celestialtree_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_celestialtree_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_celestialtree_proto_rawDescGZIP(), []int{1}
}

func (x *EmitResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_celestialtree_proto protoreflect.FileDescriptor

const file_proto_celestialtree_proto_rawDesc = "" +
	"\n" +
	"\x19proto/celestialtree.proto\x12\x10celestialtree.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x88\x01\n" +
	"\vEmitRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x18\n" +
	"\aparents\x18\x04 \x03(\x04R\aparents\"\x1e\n" +
	"\fEmitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2]\n" +
	"\x14CelestialTreeService\x12E\n" +
	"\x04Emit\x12\x1d.celestialtree.v1.EmitRequest\x1a\x1e.celestialtree.v1.EmitResponseB2Z0github.com/Mr-xiaotian/CelestialTree/proto;protob\x06proto3"

var (
	file_proto_celestialtree_proto_rawDescOnce sync.Once
	file_proto_celestialtree_proto_rawDescData []byte
)

func file_proto_celestialtree_proto_rawDescGZIP() []byte {
	file_proto_celestialtree_proto_rawDescOnce.Do(func() {
		file_proto_celestialtree_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_celestialtree_proto_rawDesc), len(file_proto_celestialtree_proto_rawDesc)))
	})
	return file_proto_celestialtree_proto_rawDescData
}

var file_proto_celestialtree_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_celestialtree_proto_goTypes = []any{
	(*EmitRequest)(nil),     // 0: celestialtree.v1.EmitRequest
	(*EmitResponse)(nil),    // 1: celestialtree.v1.EmitResponse
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_proto_celestialtree_proto_depIdxs = []int32{
	2, // 0: celestialtree.v1.EmitRequest.payload:type_name -> google.protobuf.Struct
	0, // 1: celestialtree.v1.CelestialTreeService.Emit:input_type -> celestialtree.v1.EmitRequest
	1, // 2: celestialtree.v1.CelestialTreeService.Emit:output_type -> celestialtree.v1.EmitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_celestialtree_proto_init() }
func file_proto_celestialtree_proto_init() {
	if File_proto_celestialtree_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_celestialtree_proto_rawDesc), len(file_proto_celestialtree_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_celestialtree_proto_goTypes,
		DependencyIndexes: file_proto_celestialtree_proto_depIdxs,
		MessageInfos:      file_proto_celestialtree_proto_msgTypes,
	}.Build()
	File_proto_celestialtree_proto = out.File
	file_proto_celestialtree_proto_goTypes = nil
	file_proto_celestialtree_proto_depIdxs = nil
}
