// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.5
// source: proto/celestialtree.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CelestialTreeService_Emit_FullMethodName = "/celestialtree.v1.CelestialTreeService/Emit"
)

// CelestialTreeServiceClient is the client API for CelestialTreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CelestialTreeServiceClient interface {
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error)
}

type celestialTreeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCelestialTreeServiceClient(cc grpc.ClientConnInterface) CelestialTreeServiceClient {
	return &celestialTreeServiceClient{cc}
}

func (c *celestialTreeServiceClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, CelestialTreeService_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CelestialTreeServiceServer is the server API for CelestialTreeService service.
// All implementations must embed UnimplementedCelestialTreeServiceServer
// for forward compatibility.
type CelestialTreeServiceServer interface {
	Emit(context.Context, *EmitRequest) (*EmitResponse, error)
	mustEmbedUnimplementedCelestialTreeServiceServer()
}

// UnimplementedCelestialTreeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCelestialTreeServiceServer struct{}

func (UnimplementedCelestialTreeServiceServer) Emit(context.Context, *EmitRequest) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedCelestialTreeServiceServer) mustEmbedUnimplementedCelestialTreeServiceServer() {}
func (UnimplementedCelestialTreeServiceServer) testEmbeddedByValue()                              {}

// UnsafeCelestialTreeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CelestialTreeServiceServer will
// result in compilation errors.
type UnsafeCelestialTreeServiceServer interface {
	mustEmbedUnimplementedCelestialTreeServiceServer()
}

func RegisterCelestialTreeServiceServer(s grpc.ServiceRegistrar, srv CelestialTreeServiceServer) {
	// If the following call panics, it indicates UnimplementedCelestialTreeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CelestialTreeService_ServiceDesc, srv)
}

func _CelestialTreeService_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelestialTreeServiceServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CelestialTreeService_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelestialTreeServiceServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CelestialTreeService_ServiceDesc is the grpc.ServiceDesc for CelestialTreeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CelestialTreeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "celestialtree.v1.CelestialTreeService",
	HandlerType: (*CelestialTreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _CelestialTreeService_Emit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/celestialtree.proto",
}
